# This file is for enabling GPU support on a Linux VM.
# Use it with the main docker-compose.yml file like this:
# docker compose -f docker-compose.yml -f docker-compose.gpu.yml up -d

services:
  ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
